use_frameworks!

platform :ios, '11.0'

target 'Contlo-iOS-SDK_Example' do
  pod 'Contlo-iOS-SDK', :path => '../'

  target 'Contlo-iOS-SDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.1'
    pod 'Nimble', '~> 10.0.0'
  end
end
