# Uncomment the next line to define a global platform for your project
use_frameworks!

platform :ios, '11.0'

target 'Contlo-iOS-SDK_Example' do
  pod 'Contlo-iOS-SDK', :path => '../'

  target 'Contlo-iOS-SDK_Tests' do
    inherit! :search_paths
  # Pods for NotificationService
    pod 'Quick', '~> 5.0.1'
    pod 'Nimble', '~> 10.0.0'
  end
end

target 'NotificationContent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for NotificationContent

end

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Contlo-iOS-SDK', :path => '../'
  # Pods for NotificationService


end
